[package]
name = "dragonprint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.5"
rand = "0.8.5"
substring = "1.4.5"
term_size = "0.3.2"
